/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeoRouteImport } from './routes/api/geo'
import { Route as ApiGeneratePdfRouteImport } from './routes/api/generate-pdf'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoRoute = ApiGeoRouteImport.update({
  id: '/api/geo',
  path: '/api/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePdfRoute = ApiGeneratePdfRouteImport.update({
  id: '/api/generate-pdf',
  path: '/api/generate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/geo': typeof ApiGeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/geo': typeof ApiGeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-pdf': typeof ApiGeneratePdfRoute
  '/api/geo': typeof ApiGeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/sitemap.xml'
    | '/api/generate-pdf'
    | '/api/geo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/builder' | '/sitemap.xml' | '/api/generate-pdf' | '/api/geo'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/sitemap.xml'
    | '/api/generate-pdf'
    | '/api/geo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGeneratePdfRoute: typeof ApiGeneratePdfRoute
  ApiGeoRoute: typeof ApiGeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo': {
      id: '/api/geo'
      path: '/api/geo'
      fullPath: '/api/geo'
      preLoaderRoute: typeof ApiGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-pdf': {
      id: '/api/generate-pdf'
      path: '/api/generate-pdf'
      fullPath: '/api/generate-pdf'
      preLoaderRoute: typeof ApiGeneratePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGeneratePdfRoute: ApiGeneratePdfRoute,
  ApiGeoRoute: ApiGeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
